import type { Brand, Product } from '../types'
import { roundToDecimals } from './number-format'

const INVENTORY_COLUMNS = {
  itemNumber: 0, // A / citemno
  casePack: 17, // R / cpack
  caseWeight: 108, // DE / nmweight
  unitLength: 177, // FV / nunitlen
  unitWidth: 178, // FW / nunitwid
  unitHeight: 179, // FX / nunithgt
} as const

export const EXCLUDED_ICA_BUYERS = new Set([
  '',
  'DEFAULT',
  'JOHNR',
  '#N/A',
  'NPAONE',
  'PFP',
  'PAYTONC',
  'JASON',
  'CRISTAT',
  'DAVEC',
  'DCARN',
])

export interface InventoryInfoImportResult {
  products: Product[]
  totalRows: number
  matchedRows: number
  updatedProducts: number
  skippedRows: number
}

export interface InventoryInfoItem {
  itemNumber: string
  description?: string
  upc?: string
  status?: string
  brandCode?: string
  buyer?: string
  casePack?: number
  caseWeight?: number
  caseCost?: number
  width?: number
  depth?: number
  height?: number
  weight?: number
}

export function shouldExcludeIcaBuyer(value: unknown) {
  return EXCLUDED_ICA_BUYERS.has(String(value ?? '').trim().toUpperCase())
}

const INVENTORY_BRAND_MAP: Record<string, Brand> = {
  GFN: 'gefen',
  GEFEN: 'gefen',
  HADD: 'haddar',
  HADDAR: 'haddar',
  KJC: 'kedem',
  KEDEM: 'kedem',
  TUSCANINI: 'tuscanini',
  TUS: 'tuscanini',
  LIEBERS: 'liebers',
  "LIEBER'S": 'liebers',
  OSEM: 'osem',
}

const BRAND_COLORS: Record<Brand, string> = {
  tuscanini: '#1B4D3E',
  kedem: '#991B1B',
  gefen: '#7C3AED',
  liebers: '#C41E3A',
  haddar: '#1E3A8A',
  osem: '#059669',
  other: '#64748B',
}

function normalizeItemNumber(value: unknown) {
  if (value === null || value === undefined) return ''

  const raw = String(value).trim()
  if (!raw) return ''

  return raw.endsWith('.0') ? raw.slice(0, -2) : raw
}

function parsePositiveNumber(value: unknown) {
  if (typeof value === 'number') {
    return Number.isFinite(value) && value > 0 ? value : null
  }

  if (typeof value !== 'string') return null

  const parsed = Number(value.replace(/,/g, '').trim())
  return Number.isFinite(parsed) && parsed > 0 ? parsed : null
}

function roundMetric(value: number) {
  return Math.round((value + Number.EPSILON) * 1000) / 1000
}

function buildProductMatchIndex(products: Product[]) {
  const index = new Map<string, number>()

  products.forEach((product, productIndex) => {
    if (product.autoGeneratedCase) return

    const identifiers = [
      product.kaycoItemNumber,
      product.sku,
    ]

    identifiers.forEach((identifier) => {
      const normalized = normalizeItemNumber(identifier)
      if (normalized && !index.has(normalized)) {
        index.set(normalized, productIndex)
      }
    })
  })

  return index
}

function getProductItemCode(product: Product) {
  const kaycoItemNumber = normalizeItemNumber(product.kaycoItemNumber)
  if (kaycoItemNumber) return kaycoItemNumber

  const sku = normalizeItemNumber(product.sku)
  return /^\d+$/.test(sku) ? sku : ''
}

function getInventoryProductUpdates(info: InventoryInfoItem): Partial<Product> {
  const mappedBrand = mapInventoryBrandToProductBrand(info.brandCode)
  const updates: Partial<Product> = {
    kaycoItemNumber: info.itemNumber,
  }

  if (info.upc) updates.upc = info.upc
  if (info.brandCode) updates.brandCode = info.brandCode
  if (mappedBrand) {
    updates.brand = mappedBrand
    updates.brandColor = BRAND_COLORS[mappedBrand]
  }
  if (info.buyer) updates.buyer = info.buyer
  if (info.width !== undefined) updates.width = info.width
  if (info.depth !== undefined) updates.depth = info.depth
  if (info.height !== undefined) updates.height = info.height
  if (info.casePack !== undefined) updates.unitsPerCase = info.casePack
  if (info.caseCost !== undefined) updates.caseCost = info.caseCost
  if (info.weight !== undefined) updates.weight = info.weight

  return updates
}

export function mapInventoryBrandToProductBrand(brandCode?: string) {
  return brandCode ? INVENTORY_BRAND_MAP[brandCode.toUpperCase()] ?? 'other' : undefined
}

function createProductFromInventoryInfo(info: InventoryInfoItem): Product {
  const brand = mapInventoryBrandToProductBrand(info.brandCode) ?? 'other'

  return {
    id: `inventory-${info.itemNumber}`,
    name: info.description ?? info.itemNumber,
    sku: info.itemNumber,
    upc: info.upc,
    kaycoItemNumber: info.itemNumber,
    brandCode: info.brandCode,
    buyer: info.buyer,
    brand,
    brandColor: BRAND_COLORS[brand],
    category: '',
    width: info.width ?? 0,
    height: info.height ?? 0,
    depth: info.depth ?? 0,
    weight: info.weight ?? 0,
    unitsPerCase: info.casePack,
    caseCost: info.caseCost,
    holidayTags: [],
  }
}

export function buildInventoryInfoIndex(items: InventoryInfoItem[]) {
  const index = new Map<string, InventoryInfoItem>()

  items.forEach((item) => {
    const itemNumber = normalizeItemNumber(item.itemNumber)
    if (itemNumber && !index.has(itemNumber)) {
      index.set(itemNumber, item)
    }
  })

  return index
}

export function findInventoryInfo(
  index: Map<string, InventoryInfoItem>,
  value: unknown,
) {
  const itemNumber = normalizeItemNumber(value)
  return itemNumber ? index.get(itemNumber) : undefined
}

export function mergeInventoryInfoIntoProducts(
  products: Product[],
  items: InventoryInfoItem[],
): InventoryInfoImportResult {
  const inventoryByItemNumber = buildInventoryInfoIndex(items)
  const existingProductIndexByItemNumber = buildProductMatchIndex(products)
  const nextProducts: Product[] = []
  const updatedProductIndexes = new Set<number>()

  let matchedRows = 0
  let skippedRows = products.length

  inventoryByItemNumber.forEach((info, itemNumber) => {
    const existingProductIndex = existingProductIndexByItemNumber.get(itemNumber)
    const existingProduct =
      existingProductIndex === undefined ? undefined : products[existingProductIndex]

    nextProducts.push({
      ...(existingProduct ?? createProductFromInventoryInfo(info)),
      ...getInventoryProductUpdates(info),
      id: existingProduct?.id ?? `inventory-${info.itemNumber}`,
      name: info.description ?? existingProduct?.name ?? info.itemNumber,
      sku: info.itemNumber,
      category: '',
      holidayTags: existingProduct?.holidayTags ?? [],
    })

    matchedRows++
    if (existingProductIndex !== undefined) {
      updatedProductIndexes.add(existingProductIndex)
      skippedRows--
    }
  })

  return {
    products: nextProducts,
    totalRows: items.length,
    matchedRows,
    updatedProducts: updatedProductIndexes.size,
    skippedRows,
  }
}

export function mergeInventoryInfoRowsIntoProducts(
  products: Product[],
  rows: unknown[][],
): InventoryInfoImportResult {
  const activeItems = rows.slice(1).flatMap((row) => {
    if (String(row[7] ?? '').trim() !== 'A') return []

    const itemNumber = normalizeItemNumber(row[INVENTORY_COLUMNS.itemNumber])
    if (!itemNumber) return []

    const unitsPerCase = parsePositiveNumber(row[INVENTORY_COLUMNS.casePack])
    const caseWeight = parsePositiveNumber(row[INVENTORY_COLUMNS.caseWeight])
    const unitLength = parsePositiveNumber(row[INVENTORY_COLUMNS.unitLength])
    const unitWidth = parsePositiveNumber(row[INVENTORY_COLUMNS.unitWidth])
    const unitHeight = parsePositiveNumber(row[INVENTORY_COLUMNS.unitHeight])

    return [{
      itemNumber,
      description: String(row[1] ?? '').trim() || undefined,
      upc: normalizeItemNumber(row[5]),
      status: 'A',
      brandCode: String(row[10] ?? '').trim() || undefined,
      buyer: String(row[15] ?? '').trim() || undefined,
      casePack: unitsPerCase === null ? undefined : roundMetric(unitsPerCase),
      width: unitLength === null ? undefined : roundMetric(unitLength),
      depth: unitWidth === null ? undefined : roundMetric(unitWidth),
      height: unitHeight === null ? undefined : roundMetric(unitHeight),
      weight:
        caseWeight !== null && unitsPerCase !== null
          ? roundToDecimals(caseWeight / unitsPerCase, 2)
          : undefined,
    }]
  })

  const result = mergeInventoryInfoIntoProducts(products, activeItems)
  return {
    ...result,
    totalRows: Math.max(0, rows.length - 1),
    skippedRows: Math.max(0, rows.length - 1 - activeItems.length) + result.skippedRows,
  }
}
