import type { Product, Retailer, DisplayProject, Brand } from '../types'

export const BRAND_COLORS: Record<Brand, string> = {
  tuscanini: '#1B4D3E',
  kedem: '#991B1B',
  gefen: '#7C3AED',
  liebers: '#C41E3A',
  haddar: '#1E3A8A',
  osem: '#059669',
}

export const mockProducts: Product[] = [
  // Tuscanini
  {
    id: 'prod-1',
    name: 'Extra Virgin Olive Oil 750ml',
    sku: 'TUS-EVOO-750',
    brand: 'tuscanini',
    brandColor: BRAND_COLORS.tuscanini,
    category: 'Oils',
    width: 3.5,
    height: 12,
    depth: 3.5,
    weight: 1.8,
    holidayTags: ['rosh-hashanah'],
  },
  {
    id: 'prod-2',
    name: 'Balsamic Vinegar Bronze 250ml',
    sku: 'TUS-BALS-250',
    brand: 'tuscanini',
    brandColor: BRAND_COLORS.tuscanini,
    category: 'Vinegars',
    width: 2,
    height: 8,
    depth: 2,
    weight: 0.8,
    holidayTags: [],
  },
  {
    id: 'prod-3',
    name: 'Pasta Penne 500g',
    sku: 'TUS-PEN-500',
    brand: 'tuscanini',
    brandColor: BRAND_COLORS.tuscanini,
    category: 'Pasta',
    width: 4,
    height: 9,
    depth: 2.5,
    weight: 1.1,
    holidayTags: [],
  },
  {
    id: 'prod-4',
    name: 'Tomato Sauce 680g',
    sku: 'TUS-TOM-680',
    brand: 'tuscanini',
    brandColor: BRAND_COLORS.tuscanini,
    category: 'Sauces',
    width: 3,
    height: 6,
    depth: 3,
    weight: 1.6,
    holidayTags: [],
  },

  // Kedem
  {
    id: 'prod-5',
    name: 'Sparkling Grape Juice 750ml',
    sku: 'KED-SGJ-750',
    brand: 'kedem',
    brandColor: BRAND_COLORS.kedem,
    category: 'Beverages',
    width: 3.2,
    height: 11.5,
    depth: 3.2,
    weight: 2.0,
    holidayTags: ['rosh-hashanah'],
  },
  {
    id: 'prod-6',
    name: 'Concord Grape Juice 1L',
    sku: 'KED-CGJ-1L',
    brand: 'kedem',
    brandColor: BRAND_COLORS.kedem,
    category: 'Beverages',
    width: 3.5,
    height: 10,
    depth: 3.5,
    weight: 2.4,
    modelUrl: '/models/kedem-grape-juice.glb',
    packaging: 'bottle',
    holidayTags: ['rosh-hashanah'],
  },
  {
    id: 'prod-7',
    name: 'Apple Juice 64oz',
    sku: 'KED-AJ-64',
    brand: 'kedem',
    brandColor: BRAND_COLORS.kedem,
    category: 'Beverages',
    width: 4,
    height: 10,
    depth: 4,
    weight: 4.2,
    holidayTags: ['rosh-hashanah'],
  },
  {
    id: 'prod-8',
    name: 'Tea Biscuits',
    sku: 'KED-TBSC-1',
    brand: 'kedem',
    brandColor: BRAND_COLORS.kedem,
    category: 'Snacks',
    width: 6,
    height: 3,
    depth: 2,
    weight: 0.5,
    holidayTags: [],
  },

  // Gefen
  {
    id: 'prod-9',
    name: 'Whole Hearts of Palm 14oz',
    sku: 'GEF-HOP-14',
    brand: 'gefen',
    brandColor: BRAND_COLORS.gefen,
    category: 'Condiments',
    width: 3,
    height: 5,
    depth: 3,
    weight: 1.0,
    holidayTags: [],
  },
  {
    id: 'prod-10',
    name: 'Apricot Fruit Spread 400g',
    sku: 'GEF-APR-400',
    brand: 'gefen',
    brandColor: BRAND_COLORS.gefen,
    category: 'Spreads',
    width: 3,
    height: 4.2,
    depth: 3,
    weight: 0.9,
    holidayTags: [],
  },
  {
    id: 'prod-11',
    name: 'Chestnuts Roasted',
    sku: 'GEF-CHST-1',
    brand: 'gefen',
    brandColor: BRAND_COLORS.gefen,
    category: 'Snacks',
    width: 4,
    height: 6,
    depth: 2,
    weight: 0.5,
    holidayTags: [],
  },
  {
    id: 'prod-12',
    name: 'Coconut Milk',
    sku: 'GEF-COCO-1',
    brand: 'gefen',
    brandColor: BRAND_COLORS.gefen,
    category: 'Beverages',
    width: 2.5,
    height: 4.5,
    depth: 2.5,
    weight: 0.9,
    holidayTags: [],
  },

  // Lieber's
  {
    id: 'prod-13',
    name: 'Egg Noodles Wide 400g',
    sku: 'LIE-EGN-400',
    brand: 'liebers',
    brandColor: BRAND_COLORS.liebers,
    category: 'Pasta',
    width: 5,
    height: 8,
    depth: 3,
    weight: 0.9,
    holidayTags: [],
  },
  {
    id: 'prod-14',
    name: 'Baking Cocoa',
    sku: 'LIE-COC-1',
    brand: 'liebers',
    brandColor: BRAND_COLORS.liebers,
    category: 'Baking',
    width: 3,
    height: 5,
    depth: 2,
    weight: 0.5,
    holidayTags: [],
  },
  {
    id: 'prod-15',
    name: 'Chocolate Chips',
    sku: 'LIE-CHOC-1',
    brand: 'liebers',
    brandColor: BRAND_COLORS.liebers,
    category: 'Baking',
    width: 4,
    height: 6,
    depth: 2.5,
    weight: 0.8,
    holidayTags: [],
  },
  {
    id: 'prod-16',
    name: 'Vanilla Extract',
    sku: 'LIE-VAN-1',
    brand: 'liebers',
    brandColor: BRAND_COLORS.liebers,
    category: 'Baking',
    width: 1.5,
    height: 4.5,
    depth: 1.5,
    weight: 0.3,
    holidayTags: [],
  },

  // Haddar
  {
    id: 'prod-17',
    name: 'Canola Oil 32oz',
    sku: 'HAD-CAN-32',
    brand: 'haddar',
    brandColor: BRAND_COLORS.haddar,
    category: 'Oils',
    width: 3,
    height: 9,
    depth: 3,
    weight: 2.1,
    holidayTags: [],
  },
  {
    id: 'prod-18',
    name: 'Matzo Ball Mix',
    sku: 'HAD-MTZ-1',
    brand: 'haddar',
    brandColor: BRAND_COLORS.haddar,
    category: 'Baking',
    width: 4,
    height: 6,
    depth: 2,
    weight: 0.4,
    holidayTags: ['rosh-hashanah', 'pesach'],
  },
  {
    id: 'prod-19',
    name: 'Honey 16oz',
    sku: 'HAD-HON-16',
    brand: 'haddar',
    brandColor: BRAND_COLORS.haddar,
    category: 'Condiments',
    width: 3,
    height: 5.5,
    depth: 3,
    weight: 1.2,
    holidayTags: ['rosh-hashanah'],
  },

  // Osem
  {
    id: 'prod-20',
    name: 'Pearl Couscous Original',
    sku: 'OSE-COU-1',
    brand: 'osem',
    brandColor: BRAND_COLORS.osem,
    category: 'Pasta',
    width: 4,
    height: 7,
    depth: 2.5,
    weight: 0.6,
    holidayTags: [],
  },
  {
    id: 'prod-21',
    name: 'Bamba Peanut Snack',
    sku: 'OSE-BAM-1',
    brand: 'osem',
    brandColor: BRAND_COLORS.osem,
    category: 'Snacks',
    width: 5,
    height: 8,
    depth: 3,
    weight: 0.2,
    holidayTags: [],
  },
  {
    id: 'prod-22',
    name: 'Bartenura Gnocchi 500g',
    sku: 'TUS-GNO-500',
    brand: 'tuscanini',
    brandColor: BRAND_COLORS.tuscanini,
    category: 'Pasta',
    width: 6,
    height: 8,
    depth: 2.5,
    weight: 1.1,
    modelUrl: '/models/bartenura-gnocchi.glb',
    packaging: 'bag',
    holidayTags: [],
  },
]

export const mockRetailers: Retailer[] = [
  {
    id: 'ret-1',
    name: 'Walmart',
    status: 'active',
    tier: 'enterprise',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 4700,
    regions: ['Northeast', 'Southeast', 'Midwest', 'West', 'Southwest'],
    headquartersCity: 'Bentonville',
    headquartersState: 'AR',
    accountManager: 'David Greenfield',
    contractStart: '2024-01-15',
    contractEnd: '2026-12-31',
    website: 'walmart.com',
    tags: ['top-account', 'holiday-priority', 'endcap-eligible'],
    contacts: [
      { id: 'c-1', name: 'Jennifer Walsh', title: 'Category Manager — Ethnic Foods', email: 'j.walsh@walmart.com', phone: '(479) 555-0142', isPrimary: true },
      { id: 'c-2', name: 'Marcus Rivera', title: 'Display Compliance Lead', email: 'm.rivera@walmart.com', phone: '(479) 555-0198', isPrimary: false },
      { id: 'c-3', name: 'Sarah Kim', title: 'Procurement Specialist', email: 's.kim@walmart.com', phone: '(479) 555-0167', isPrimary: false },
    ],
    authorizedItems: [
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-03-01', lastOrderDate: '2026-03-15', avgMonthlyUnits: 2400, marginPercent: 34.2 },
      { productId: 'prod-5', productName: 'Sparkling Grape Juice 750ml', sku: 'KED-SGJ-750', brand: 'kedem', status: 'authorized', authorizedDate: '2024-01-15', lastOrderDate: '2026-03-20', avgMonthlyUnits: 5200, marginPercent: 28.5 },
      { productId: 'prod-6', productName: 'Concord Grape Juice 1L', sku: 'KED-CGJ-1L', brand: 'kedem', status: 'authorized', authorizedDate: '2024-01-15', lastOrderDate: '2026-03-18', avgMonthlyUnits: 4100, marginPercent: 26.8 },
      { productId: 'prod-7', productName: 'Apple Juice 64oz', sku: 'KED-AJ-64', brand: 'kedem', status: 'authorized', authorizedDate: '2024-06-01', lastOrderDate: '2026-02-28', avgMonthlyUnits: 3800, marginPercent: 31.0 },
      { productId: 'prod-17', productName: 'Canola Oil 32oz', sku: 'HAD-CAN-32', brand: 'haddar', status: 'authorized', authorizedDate: '2025-01-10', lastOrderDate: '2026-03-12', avgMonthlyUnits: 1900, marginPercent: 22.4 },
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'authorized', authorizedDate: '2024-08-01', lastOrderDate: '2026-03-22', avgMonthlyUnits: 6100, marginPercent: 38.7 },
      { productId: 'prod-20', productName: 'Pearl Couscous Original', sku: 'OSE-COU-1', brand: 'osem', status: 'authorized', authorizedDate: '2025-02-01', lastOrderDate: '2026-03-10', avgMonthlyUnits: 1200, marginPercent: 29.5 },
      { productId: 'prod-3', productName: 'Pasta Penne 500g', sku: 'TUS-PEN-500', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-03-01', avgMonthlyUnits: 0, marginPercent: 32.1 },
      { productId: 'prod-21', productName: 'Bamba Peanut Snack', sku: 'OSE-BAM-1', brand: 'osem', status: 'authorized', authorizedDate: '2024-11-01', lastOrderDate: '2026-03-19', avgMonthlyUnits: 8500, marginPercent: 42.3 },
      { productId: 'prod-4', productName: 'Tomato Sauce 680g', sku: 'TUS-TOM-680', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-05-15', lastOrderDate: '2026-02-25', avgMonthlyUnits: 3200, marginPercent: 35.6 },
      { productId: 'prod-18', productName: 'Matzo Ball Mix', sku: 'HAD-MTZ-1', brand: 'haddar', status: 'authorized', authorizedDate: '2024-03-01', lastOrderDate: '2026-03-14', avgMonthlyUnits: 2800, marginPercent: 40.1 },
      { productId: 'prod-9', productName: 'Whole Hearts of Palm 14oz', sku: 'GEF-HOP-14', brand: 'gefen', status: 'discontinued', authorizedDate: '2023-06-01', lastOrderDate: '2025-11-30', avgMonthlyUnits: 0, marginPercent: 18.2 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-1', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-15', nextAuditDate: '2026-08-15' },
      { id: 'comp-2', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-20', nextAuditDate: '2026-07-20' },
      { id: 'comp-3', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-03-01', nextAuditDate: '2026-09-01' },
      { id: 'comp-4', requirement: 'GTIN/UPC Barcode Verification', status: 'compliant', lastAuditDate: '2026-02-01', nextAuditDate: '2026-08-01' },
      { id: 'comp-5', requirement: 'Supplier Insurance & Liability', status: 'action-required', lastAuditDate: '2025-12-01', nextAuditDate: '2026-06-01', notes: 'Updated COI needed by June — current policy expiring' },
    ],
    performance: { totalRevenueMTD: 284500, totalRevenueYTD: 1842000, avgOrderValue: 12800, fillRate: 97.2, onTimeDelivery: 94.8, returnRate: 1.3, displayComplianceScore: 92 },
    displayHistory: [
      { id: 'dh-1', projectName: 'RH 2026 — Walmart', holiday: 'rosh-hashanah', createdAt: '2026-03-01', status: 'active', tierCount: 4, productCount: 7 },
      { id: 'dh-2', projectName: 'Pesach 2026 — Walmart', holiday: 'pesach', createdAt: '2026-01-15', status: 'draft', tierCount: 4, productCount: 3 },
      { id: 'dh-3', projectName: 'RH 2025 — Walmart', holiday: 'rosh-hashanah', createdAt: '2025-03-10', status: 'completed', tierCount: 4, productCount: 8 },
      { id: 'dh-4', projectName: 'Pesach 2025 — Walmart', holiday: 'pesach', createdAt: '2025-01-05', status: 'completed', tierCount: 3, productCount: 6 },
    ],
    notes: 'Largest account by volume. Holiday endcap program renewed through 2026. Requires 4-week lead time on new item authorizations.',
  },
  {
    id: 'ret-2',
    name: 'Costco',
    status: 'active',
    tier: 'enterprise',
    defaultTierCount: 3,
    maxDisplayHeight: 72,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 591,
    regions: ['Northeast', 'West', 'Southeast'],
    headquartersCity: 'Issaquah',
    headquartersState: 'WA',
    accountManager: 'David Greenfield',
    contractStart: '2024-06-01',
    contractEnd: '2027-05-31',
    website: 'costco.com',
    tags: ['top-account', 'bulk-format', 'warehouse-club'],
    contacts: [
      { id: 'c-4', name: 'Brian Cho', title: 'Assistant Buyer — Specialty Foods', email: 'b.cho@costco.com', phone: '(425) 555-0231', isPrimary: true },
      { id: 'c-5', name: 'Amanda Torres', title: 'Vendor Relations Manager', email: 'a.torres@costco.com', phone: '(425) 555-0289', isPrimary: false },
    ],
    authorizedItems: [
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-06-15', lastOrderDate: '2026-03-10', avgMonthlyUnits: 4800, marginPercent: 29.1 },
      { productId: 'prod-5', productName: 'Sparkling Grape Juice 750ml', sku: 'KED-SGJ-750', brand: 'kedem', status: 'authorized', authorizedDate: '2024-06-15', lastOrderDate: '2026-03-22', avgMonthlyUnits: 7200, marginPercent: 24.5 },
      { productId: 'prod-6', productName: 'Concord Grape Juice 1L', sku: 'KED-CGJ-1L', brand: 'kedem', status: 'authorized', authorizedDate: '2024-06-15', lastOrderDate: '2026-03-18', avgMonthlyUnits: 6500, marginPercent: 23.2 },
      { productId: 'prod-21', productName: 'Bamba Peanut Snack', sku: 'OSE-BAM-1', brand: 'osem', status: 'authorized', authorizedDate: '2025-01-10', lastOrderDate: '2026-03-20', avgMonthlyUnits: 12000, marginPercent: 38.9 },
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'authorized', authorizedDate: '2024-09-01', lastOrderDate: '2026-03-15', avgMonthlyUnits: 8400, marginPercent: 35.2 },
      { productId: 'prod-2', productName: 'Balsamic Vinegar Bronze 250ml', sku: 'TUS-BALS-250', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-02-20', avgMonthlyUnits: 0, marginPercent: 36.8 },
      { productId: 'prod-20', productName: 'Pearl Couscous Original', sku: 'OSE-COU-1', brand: 'osem', status: 'authorized', authorizedDate: '2025-03-01', lastOrderDate: '2026-03-08', avgMonthlyUnits: 3200, marginPercent: 31.4 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-6', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-01-10', nextAuditDate: '2026-07-10' },
      { id: 'comp-7', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-02-05', nextAuditDate: '2026-08-05' },
      { id: 'comp-8', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-01-15', nextAuditDate: '2026-07-15' },
      { id: 'comp-9', requirement: 'Warehouse Club Packaging Standards', status: 'pending-review', lastAuditDate: '2025-11-20', nextAuditDate: '2026-05-20', notes: 'New multi-pack requirements under review for Q3' },
    ],
    performance: { totalRevenueMTD: 198700, totalRevenueYTD: 1156000, avgOrderValue: 24500, fillRate: 98.1, onTimeDelivery: 96.5, returnRate: 0.8, displayComplianceScore: 96 },
    displayHistory: [
      { id: 'dh-5', projectName: 'RH 2026 — Costco', holiday: 'rosh-hashanah', createdAt: '2026-02-20', status: 'draft', tierCount: 3, productCount: 5 },
      { id: 'dh-6', projectName: 'RH 2025 — Costco', holiday: 'rosh-hashanah', createdAt: '2025-02-15', status: 'completed', tierCount: 3, productCount: 6 },
    ],
    notes: 'Requires bulk/club-pack formats. 72" max display height allows taller builds. High velocity on Bamba and grape juice.',
  },
  {
    id: 'ret-3',
    name: 'ShopRite',
    status: 'active',
    tier: 'premium',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 320,
    regions: ['Northeast', 'Mid-Atlantic'],
    headquartersCity: 'Keasbey',
    headquartersState: 'NJ',
    accountManager: 'Rachel Hoffman',
    contractStart: '2024-04-01',
    contractEnd: '2026-03-31',
    website: 'shoprite.com',
    tags: ['kosher-strong', 'regional-key', 'cooperative'],
    contacts: [
      { id: 'c-6', name: 'Michael Stern', title: 'VP Ethnic & Specialty', email: 'm.stern@shoprite.com', phone: '(732) 555-0144', isPrimary: true },
      { id: 'c-7', name: 'Lisa Parikh', title: 'Category Analyst', email: 'l.parikh@shoprite.com', phone: '(732) 555-0177', isPrimary: false },
      { id: 'c-8', name: 'Dan Cooper', title: 'Store Operations Director', email: 'd.cooper@shoprite.com', phone: '(732) 555-0199', isPrimary: false },
    ],
    authorizedItems: [
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 36.4 },
      { productId: 'prod-2', productName: 'Balsamic Vinegar Bronze 250ml', sku: 'TUS-BALS-250', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-18', avgMonthlyUnits: 950, marginPercent: 38.2 },
      { productId: 'prod-3', productName: 'Pasta Penne 500g', sku: 'TUS-PEN-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-07-01', lastOrderDate: '2026-03-15', avgMonthlyUnits: 1400, marginPercent: 33.5 },
      { productId: 'prod-4', productName: 'Tomato Sauce 680g', sku: 'TUS-TOM-680', brand: 'tuscanini', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-22', avgMonthlyUnits: 2200, marginPercent: 37.8 },
      { productId: 'prod-5', productName: 'Sparkling Grape Juice 750ml', sku: 'KED-SGJ-750', brand: 'kedem', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-21', avgMonthlyUnits: 3800, marginPercent: 30.1 },
      { productId: 'prod-6', productName: 'Concord Grape Juice 1L', sku: 'KED-CGJ-1L', brand: 'kedem', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-19', avgMonthlyUnits: 3100, marginPercent: 28.7 },
      { productId: 'prod-8', productName: 'Tea Biscuits', sku: 'KED-TBSC-1', brand: 'kedem', status: 'authorized', authorizedDate: '2024-09-15', lastOrderDate: '2026-03-10', avgMonthlyUnits: 1600, marginPercent: 42.0 },
      { productId: 'prod-9', productName: 'Whole Hearts of Palm 14oz', sku: 'GEF-HOP-14', brand: 'gefen', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-12', avgMonthlyUnits: 780, marginPercent: 25.9 },
      { productId: 'prod-10', productName: 'Apricot Fruit Spread 400g', sku: 'GEF-APR-400', brand: 'gefen', status: 'authorized', authorizedDate: '2024-08-01', lastOrderDate: '2026-02-28', avgMonthlyUnits: 620, marginPercent: 34.1 },
      { productId: 'prod-13', productName: 'Egg Noodles Wide 400g', sku: 'LIE-EGN-400', brand: 'liebers', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-17', avgMonthlyUnits: 1100, marginPercent: 30.5 },
      { productId: 'prod-14', productName: 'Baking Cocoa', sku: 'LIE-COC-1', brand: 'liebers', status: 'authorized', authorizedDate: '2025-01-15', lastOrderDate: '2026-03-08', avgMonthlyUnits: 540, marginPercent: 44.2 },
      { productId: 'prod-15', productName: 'Chocolate Chips', sku: 'LIE-CHOC-1', brand: 'liebers', status: 'authorized', authorizedDate: '2024-10-01', lastOrderDate: '2026-03-14', avgMonthlyUnits: 890, marginPercent: 39.7 },
      { productId: 'prod-17', productName: 'Canola Oil 32oz', sku: 'HAD-CAN-32', brand: 'haddar', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1500, marginPercent: 24.3 },
      { productId: 'prod-18', productName: 'Matzo Ball Mix', sku: 'HAD-MTZ-1', brand: 'haddar', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-16', avgMonthlyUnits: 2100, marginPercent: 41.8 },
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'authorized', authorizedDate: '2024-04-01', lastOrderDate: '2026-03-22', avgMonthlyUnits: 4500, marginPercent: 40.2 },
      { productId: 'prod-21', productName: 'Bamba Peanut Snack', sku: 'OSE-BAM-1', brand: 'osem', status: 'authorized', authorizedDate: '2024-11-01', lastOrderDate: '2026-03-19', avgMonthlyUnits: 5200, marginPercent: 43.5 },
      { productId: 'prod-11', productName: 'Chestnuts Roasted', sku: 'GEF-CHST-1', brand: 'gefen', status: 'pending', authorizedDate: '2026-03-15', avgMonthlyUnits: 0, marginPercent: 28.0 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-10', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-20', nextAuditDate: '2026-08-20' },
      { id: 'comp-11', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-15', nextAuditDate: '2026-07-15' },
      { id: 'comp-12', requirement: 'Kosher Certification Documentation', status: 'compliant', lastAuditDate: '2026-03-05', nextAuditDate: '2026-09-05' },
      { id: 'comp-13', requirement: 'Co-op Advertising Compliance', status: 'compliant', lastAuditDate: '2026-01-30', nextAuditDate: '2026-07-30' },
      { id: 'comp-14', requirement: 'GTIN/UPC Barcode Verification', status: 'compliant', lastAuditDate: '2026-02-10', nextAuditDate: '2026-08-10' },
    ],
    performance: { totalRevenueMTD: 156200, totalRevenueYTD: 987000, avgOrderValue: 8900, fillRate: 95.4, onTimeDelivery: 93.1, returnRate: 1.8, displayComplianceScore: 88 },
    displayHistory: [
      { id: 'dh-7', projectName: 'RH 2026 — ShopRite', holiday: 'rosh-hashanah', createdAt: '2026-02-28', status: 'active', tierCount: 4, productCount: 9 },
      { id: 'dh-8', projectName: 'Pesach 2026 — ShopRite', holiday: 'pesach', createdAt: '2026-01-20', status: 'draft', tierCount: 4, productCount: 4 },
      { id: 'dh-9', projectName: 'RH 2025 — ShopRite', holiday: 'rosh-hashanah', createdAt: '2025-03-05', status: 'completed', tierCount: 4, productCount: 10 },
      { id: 'dh-10', projectName: 'Sukkos 2025 — ShopRite', holiday: 'sukkos', createdAt: '2025-07-15', status: 'completed', tierCount: 3, productCount: 5 },
      { id: 'dh-11', projectName: 'Pesach 2025 — ShopRite', holiday: 'pesach', createdAt: '2025-01-10', status: 'completed', tierCount: 4, productCount: 8 },
    ],
    notes: 'Strongest kosher aisle penetration in the tri-state area. Co-op owned — each store can make independent display decisions. Key account for Tuscanini line.',
  },
  {
    id: 'ret-4',
    name: 'Stop & Shop',
    status: 'active',
    tier: 'standard',
    defaultTierCount: 3,
    maxDisplayHeight: 54,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 400,
    regions: ['Northeast', 'New England'],
    headquartersCity: 'Quincy',
    headquartersState: 'MA',
    accountManager: 'Rachel Hoffman',
    contractStart: '2025-01-01',
    contractEnd: '2026-12-31',
    website: 'stopandshop.com',
    tags: ['growing-account', 'northeast-focus'],
    contacts: [
      { id: 'c-9', name: "Karen O'Brien", title: 'Category Manager — International', email: 'k.obrien@stopandshop.com', phone: '(617) 555-0188', isPrimary: true },
      { id: 'c-10', name: 'James Petrov', title: 'Merchandising Coordinator', email: 'j.petrov@stopandshop.com', phone: '(617) 555-0204', isPrimary: false },
    ],
    authorizedItems: [
      { productId: 'prod-5', productName: 'Sparkling Grape Juice 750ml', sku: 'KED-SGJ-750', brand: 'kedem', status: 'authorized', authorizedDate: '2025-01-15', lastOrderDate: '2026-03-18', avgMonthlyUnits: 1900, marginPercent: 29.8 },
      { productId: 'prod-6', productName: 'Concord Grape Juice 1L', sku: 'KED-CGJ-1L', brand: 'kedem', status: 'authorized', authorizedDate: '2025-01-15', lastOrderDate: '2026-03-15', avgMonthlyUnits: 1600, marginPercent: 27.5 },
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'authorized', authorizedDate: '2025-03-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 2200, marginPercent: 37.4 },
      { productId: 'prod-21', productName: 'Bamba Peanut Snack', sku: 'OSE-BAM-1', brand: 'osem', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-19', avgMonthlyUnits: 3100, marginPercent: 41.2 },
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-03-10', avgMonthlyUnits: 0, marginPercent: 35.0 },
      { productId: 'prod-18', productName: 'Matzo Ball Mix', sku: 'HAD-MTZ-1', brand: 'haddar', status: 'authorized', authorizedDate: '2025-01-15', lastOrderDate: '2026-03-12', avgMonthlyUnits: 900, marginPercent: 39.5 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-15', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-01-25', nextAuditDate: '2026-07-25' },
      { id: 'comp-16', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-02-10', nextAuditDate: '2026-08-10' },
      { id: 'comp-17', requirement: 'Kosher Certification Documentation', status: 'action-required', lastAuditDate: '2025-10-15', nextAuditDate: '2026-04-15', notes: 'Renewal documentation pending for 3 Haddar SKUs' },
    ],
    performance: { totalRevenueMTD: 67800, totalRevenueYTD: 412000, avgOrderValue: 5400, fillRate: 91.3, onTimeDelivery: 89.7, returnRate: 2.4, displayComplianceScore: 78 },
    displayHistory: [
      { id: 'dh-12', projectName: 'RH 2026 — Stop & Shop', holiday: 'rosh-hashanah', createdAt: '2026-03-05', status: 'draft', tierCount: 3, productCount: 4 },
      { id: 'dh-13', projectName: 'RH 2025 — Stop & Shop', holiday: 'rosh-hashanah', createdAt: '2025-03-15', status: 'completed', tierCount: 3, productCount: 5 },
    ],
    notes: 'Growing account. Expanding kosher section in NE stores. Lower display height limit (54") — plan tiers accordingly.',
  },
  {
    id: 'ret-5',
    name: 'Kroger',
    status: 'active',
    tier: 'premium',
    defaultTierCount: 4,
    maxDisplayHeight: 60,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 2750,
    regions: ['Midwest', 'Southeast', 'Southwest', 'West'],
    headquartersCity: 'Cincinnati',
    headquartersState: 'OH',
    accountManager: 'David Greenfield',
    contractStart: '2025-06-01',
    contractEnd: '2027-05-31',
    website: 'kroger.com',
    tags: ['new-2025', 'high-potential', 'multi-banner'],
    contacts: [
      { id: 'c-11', name: 'Patricia Holmes', title: 'Director of Specialty Procurement', email: 'p.holmes@kroger.com', phone: '(513) 555-0312', isPrimary: true },
      { id: 'c-12', name: 'Robert Yang', title: 'Display Program Manager', email: 'r.yang@kroger.com', phone: '(513) 555-0345', isPrimary: false },
    ],
    authorizedItems: [
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-15', lastOrderDate: '2026-03-18', avgMonthlyUnits: 1400, marginPercent: 33.8 },
      { productId: 'prod-5', productName: 'Sparkling Grape Juice 750ml', sku: 'KED-SGJ-750', brand: 'kedem', status: 'authorized', authorizedDate: '2025-06-15', lastOrderDate: '2026-03-20', avgMonthlyUnits: 2800, marginPercent: 27.9 },
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'authorized', authorizedDate: '2025-08-01', lastOrderDate: '2026-03-15', avgMonthlyUnits: 3200, marginPercent: 36.5 },
      { productId: 'prod-21', productName: 'Bamba Peanut Snack', sku: 'OSE-BAM-1', brand: 'osem', status: 'authorized', authorizedDate: '2025-09-01', lastOrderDate: '2026-03-22', avgMonthlyUnits: 4600, marginPercent: 40.8 },
      { productId: 'prod-4', productName: 'Tomato Sauce 680g', sku: 'TUS-TOM-680', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-03-01', avgMonthlyUnits: 0, marginPercent: 34.2 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-18', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2026-02-28', nextAuditDate: '2026-08-28' },
      { id: 'comp-19', requirement: 'Product Labeling (FDA)', status: 'compliant', lastAuditDate: '2026-01-20', nextAuditDate: '2026-07-20' },
      { id: 'comp-20', requirement: 'Kosher Certification Documentation', status: 'pending-review', lastAuditDate: '2025-12-15', nextAuditDate: '2026-06-15', notes: 'Initial certification review in progress' },
    ],
    performance: { totalRevenueMTD: 112400, totalRevenueYTD: 645000, avgOrderValue: 9800, fillRate: 94.6, onTimeDelivery: 92.3, returnRate: 1.5, displayComplianceScore: 85 },
    displayHistory: [
      { id: 'dh-14', projectName: 'RH 2026 — Kroger', holiday: 'rosh-hashanah', createdAt: '2026-03-10', status: 'draft', tierCount: 4, productCount: 4 },
    ],
    notes: 'New account as of mid-2025. Multi-banner retailer (Kroger, Ralphs, Fred Meyer, Harris Teeter). Huge upside potential.',
  },
  {
    id: 'ret-6',
    name: 'Whole Foods',
    status: 'pending',
    tier: 'premium',
    defaultTierCount: 3,
    maxDisplayHeight: 56,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 530,
    regions: ['Northeast', 'West', 'Southeast', 'Southwest'],
    headquartersCity: 'Austin',
    headquartersState: 'TX',
    accountManager: 'Rachel Hoffman',
    contractStart: '2026-04-01',
    contractEnd: '2028-03-31',
    website: 'wholefoodsmarket.com',
    tags: ['premium-positioning', 'organic-focus', 'onboarding'],
    contacts: [
      { id: 'c-13', name: 'Emily Chen', title: 'Global Buyer — Specialty Grocery', email: 'e.chen@wholefoods.com', phone: '(512) 555-0401', isPrimary: true },
    ],
    authorizedItems: [
      { productId: 'prod-1', productName: 'Extra Virgin Olive Oil 750ml', sku: 'TUS-EVOO-750', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-04-01', avgMonthlyUnits: 0, marginPercent: 38.5 },
      { productId: 'prod-2', productName: 'Balsamic Vinegar Bronze 250ml', sku: 'TUS-BALS-250', brand: 'tuscanini', status: 'pending', authorizedDate: '2026-04-01', avgMonthlyUnits: 0, marginPercent: 41.2 },
      { productId: 'prod-20', productName: 'Pearl Couscous Original', sku: 'OSE-COU-1', brand: 'osem', status: 'pending', authorizedDate: '2026-04-01', avgMonthlyUnits: 0, marginPercent: 33.0 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-21', requirement: 'Pallet Display Height Standards', status: 'pending-review', lastAuditDate: '2026-03-20', nextAuditDate: '2026-09-20', notes: 'Initial compliance review scheduled' },
      { id: 'comp-22', requirement: 'Organic/Non-GMO Verification', status: 'pending-review', lastAuditDate: '2026-03-25', nextAuditDate: '2026-06-25', notes: 'Required for Whole Foods — documentation submitted' },
    ],
    performance: { totalRevenueMTD: 0, totalRevenueYTD: 0, avgOrderValue: 0, fillRate: 0, onTimeDelivery: 0, returnRate: 0, displayComplianceScore: 0 },
    displayHistory: [],
    notes: 'Onboarding in progress. Premium positioning — Tuscanini line is the lead. Strict quality and labeling standards.',
  },
  {
    id: 'ret-7',
    name: 'ALDI',
    status: 'inactive',
    tier: 'standard',
    defaultTierCount: 3,
    maxDisplayHeight: 54,
    palletDimensions: { width: 48, depth: 40, height: 6 },
    storeCount: 2300,
    regions: ['Midwest', 'Southeast', 'Northeast'],
    headquartersCity: 'Batavia',
    headquartersState: 'IL',
    accountManager: 'David Greenfield',
    contractStart: '2023-01-01',
    contractEnd: '2025-12-31',
    website: 'aldi.us',
    tags: ['contract-expired', 'review-q2'],
    contacts: [
      { id: 'c-14', name: 'Thomas Weber', title: 'Buying Director', email: 't.weber@aldi.us', phone: '(630) 555-0178', isPrimary: true },
    ],
    authorizedItems: [
      { productId: 'prod-19', productName: 'Honey 16oz', sku: 'HAD-HON-16', brand: 'haddar', status: 'discontinued', authorizedDate: '2023-03-01', lastOrderDate: '2025-10-15', avgMonthlyUnits: 0, marginPercent: 19.5 },
      { productId: 'prod-17', productName: 'Canola Oil 32oz', sku: 'HAD-CAN-32', brand: 'haddar', status: 'discontinued', authorizedDate: '2023-03-01', lastOrderDate: '2025-09-30', avgMonthlyUnits: 0, marginPercent: 16.8 },
      { productId: 'prod-22', productName: 'Bartenura Gnocchi 500g', sku: 'TUS-GNO-500', brand: 'tuscanini', status: 'authorized', authorizedDate: '2025-06-01', lastOrderDate: '2026-03-20', avgMonthlyUnits: 1800, marginPercent: 35.0 },
    ],
    compliance: [
      { id: 'comp-23', requirement: 'Pallet Display Height Standards', status: 'compliant', lastAuditDate: '2025-08-15', nextAuditDate: '2026-02-15' },
    ],
    performance: { totalRevenueMTD: 0, totalRevenueYTD: 0, avgOrderValue: 0, fillRate: 0, onTimeDelivery: 0, returnRate: 0, displayComplianceScore: 0 },
    displayHistory: [
      { id: 'dh-15', projectName: 'RH 2025 — ALDI', holiday: 'rosh-hashanah', createdAt: '2025-02-20', status: 'completed', tierCount: 3, productCount: 2 },
    ],
    notes: 'Contract expired Dec 2025. Low margins made the relationship difficult. Under review for potential renewal with better terms in Q2 2026.',
  },
]

export const mockProject: DisplayProject = {
  id: 'proj-1',
  name: 'RH 2026 — Walmart',
  retailerId: 'ret-1',
  holiday: 'rosh-hashanah',
  season: 'rosh-hashanah',
  tierCount: 4,
  palletType: 'full',
  lipColor: '#1E3A8A',
  branding: {
    lipText: 'ALL YOUR HOLIDAY NEEDS',
    lipTextColor: '#FFFFFF',
    headerText: 'ROSH\nHASHANAH',
    headerTextColor: '#FFFFFF',
    headerBackgroundColor: '#EF4444',
  },
  placements: [
    {
      id: 'place-1',
      slotId: '1-0',
      width: 3.2,
      height: 11.5,
      depth: 3.2,
      color: BRAND_COLORS.kedem,
      label: 'Sparkling Grape Juice 750ml',
      sku: 'KED-SGJ-750',
    },
    {
      id: 'place-2',
      slotId: '1-1',
      width: 3.5,
      height: 10,
      depth: 3.5,
      color: BRAND_COLORS.kedem,
      label: 'Concord Grape Juice 1L',
      sku: 'KED-CGJ-1L',
    },
    {
      id: 'place-3',
      slotId: '2-0',
      width: 3,
      height: 5.5,
      depth: 3,
      color: BRAND_COLORS.haddar,
      label: 'Honey 16oz',
      sku: 'HAD-HON-16',
    },
    {
      id: 'place-4',
      slotId: '2-1',
      width: 3.5,
      height: 12,
      depth: 3.5,
      color: BRAND_COLORS.tuscanini,
      label: 'Extra Virgin Olive Oil 750ml',
      sku: 'TUS-EVOO-750',
    },
    {
      id: 'place-5',
      slotId: '3-0',
      width: 4,
      height: 6,
      depth: 2,
      color: BRAND_COLORS.haddar,
      label: 'Matzo Ball Mix',
      sku: 'HAD-MTZ-1',
    },
    {
      id: 'place-6',
      slotId: '3-1',
      width: 4,
      height: 10,
      depth: 4,
      color: BRAND_COLORS.kedem,
      label: 'Apple Juice 64oz',
      sku: 'KED-AJ-64',
    },
    {
      id: 'place-7',
      slotId: '4-0',
      width: 3,
      height: 6,
      depth: 3,
      color: BRAND_COLORS.tuscanini,
      label: 'Tomato Sauce 680g',
      sku: 'TUS-TOM-680',
    },
  ],
  createdAt: Date.now(),
  updatedAt: Date.now(),
}

export const mockProjects: DisplayProject[] = [
  mockProject,
  {
    id: 'proj-2',
    name: 'Pesach 2026 - Walmart',
    retailerId: 'ret-1',
    holiday: 'pesach',
    season: 'pesach',
    tierCount: 4,
    palletType: 'full',
    lipColor: '#0F766E',
    branding: {
      lipText: 'PASSOVER ESSENTIALS',
      lipTextColor: '#FFFFFF',
      headerText: 'PESACH',
      headerTextColor: '#FFFFFF',
      headerBackgroundColor: '#0F766E',
    },
    placements: [
      {
        id: 'place-8',
        slotId: '1-0',
        width: 4,
        height: 6,
        depth: 2,
        color: BRAND_COLORS.haddar,
        label: 'Matzo Ball Mix',
        sku: 'HAD-MTZ-1',
      },
      {
        id: 'place-9',
        slotId: '1-1',
        width: 5,
        height: 8,
        depth: 3,
        color: BRAND_COLORS.liebers,
        label: 'Egg Noodles Wide 400g',
        sku: 'LIE-EGN-400',
      },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 30,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    id: 'proj-3',
    name: 'Rosh Hashanah 2026 - ShopRite',
    retailerId: 'ret-3',
    holiday: 'rosh-hashanah',
    season: 'rosh-hashanah',
    tierCount: 4,
    palletType: 'half',
    lipColor: '#9A3412',
    branding: {
      lipText: 'HOLIDAY FAVORITES',
      lipTextColor: '#FFFFFF',
      headerText: 'ROSH\nHASHANAH',
      headerTextColor: '#FFFFFF',
      headerBackgroundColor: '#9A3412',
    },
    placements: [
      {
        id: 'place-10',
        slotId: '1-0',
        width: 3.2,
        height: 11.5,
        depth: 3.2,
        color: BRAND_COLORS.kedem,
        label: 'Sparkling Grape Juice 750ml',
        sku: 'KED-SGJ-750',
      },
      {
        id: 'place-11',
        slotId: '2-0',
        width: 3,
        height: 9,
        depth: 3,
        color: BRAND_COLORS.haddar,
        label: 'Canola Oil 32oz',
        sku: 'HAD-CAN-32',
      },
    ],
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
]
