import type { Product } from '../types'
import { calculateCaseWeight, resolveProductDimensions } from './dimensionEngine'
import { generateCaseVariants, getCaseItemCount } from '../components/PalletDisplay/products/caseUtils'

function normalizeSourceProduct(product: Product): Product {
  if (product.caseConfig) {
    return {
      ...product,
      variantType: 'case',
      parentProductId: product.parentProductId ?? product.caseConfig.unitProductId,
      autoGeneratedCase: product.autoGeneratedCase ?? false,
    }
  }

  return {
    ...product,
    variantType: 'single',
    parentProductId: product.parentProductId ?? product.id,
    autoGeneratedCase: false,
  }
}

function buildGeneratedCaseProduct(baseProduct: Product, generated: ReturnType<typeof generateCaseVariants>[number]) {
  const dimensions = resolveProductDimensions(
    {
      ...baseProduct,
      caseConfig: generated.caseConfig,
      width: generated.width,
      height: generated.height,
      depth: generated.depth,
      variantType: 'case',
      parentProductId: baseProduct.id,
      autoGeneratedCase: true,
    },
    [baseProduct],
  )

  const itemCount = getCaseItemCount(generated.caseConfig.layout)

  return {
    id: `${baseProduct.id}-case-${itemCount}`,
    name: generated.name,
    sku: `${baseProduct.sku}-CASE${itemCount}`,
    brand: baseProduct.brand,
    brandColor: baseProduct.brandColor,
    category: baseProduct.category,
    width: dimensions.width,
    height: dimensions.height,
    depth: dimensions.depth,
    weight: calculateCaseWeight(baseProduct.weight, generated.caseConfig.layout, dimensions),
    imageUrl: undefined,
    modelUrl: undefined,
    packaging: 'box' as const,
    variantType: 'case' as const,
    parentProductId: baseProduct.id,
    autoGeneratedCase: true,
    caseConfig: generated.caseConfig,
    holidayTags: baseProduct.holidayTags,
  } satisfies Product
}

export function normalizeProductsWithVariants(products: Product[]) {
  const sourceProducts = products.filter((product) => !product.autoGeneratedCase)
  const normalizedSources = sourceProducts.map(normalizeSourceProduct)

  const generatedCases: Product[] = []

  normalizedSources.forEach((product) => {
    if (product.caseConfig) return

    const existingCaseVariants = normalizedSources.filter(
      (candidate) =>
        candidate.caseConfig &&
        (candidate.parentProductId === product.id ||
          candidate.caseConfig.unitProductId === product.id),
    )
    const existingCounts = new Set(
      existingCaseVariants.map((candidate) =>
        getCaseItemCount(candidate.caseConfig!.layout),
      ),
    )

    generateCaseVariants(product).forEach((generated) => {
      const count = getCaseItemCount(generated.caseConfig.layout)
      if (existingCounts.has(count)) return
      generatedCases.push(buildGeneratedCaseProduct(product, generated))
    })
  })

  const ordered: Product[] = []
  normalizedSources.forEach((product) => {
    ordered.push(product)

    const relatedManualCases = normalizedSources.filter(
      (candidate) =>
        candidate.caseConfig &&
        candidate.id !== product.id &&
        candidate.parentProductId === product.id,
    )

    relatedManualCases.forEach((candidate) => {
      if (!ordered.some((entry) => entry.id === candidate.id)) {
        ordered.push(candidate)
      }
    })

    generatedCases
      .filter((candidate) => candidate.parentProductId === product.id)
      .forEach((candidate) => ordered.push(candidate))
  })

  const seen = new Set<string>()
  return ordered.filter((product) => {
    if (seen.has(product.id)) return false
    seen.add(product.id)
    return true
  })
}
