import type { Product } from '../types'

function normalizeSourceProduct(product: Product): Product {
  if (product.caseConfig) {
    return {
      ...product,
      variantType: 'case',
      parentProductId: product.parentProductId ?? product.caseConfig.unitProductId,
      autoGeneratedCase: product.autoGeneratedCase ?? false,
    }
  }

  return {
    ...product,
    variantType: 'single',
    parentProductId: product.parentProductId ?? product.id,
    autoGeneratedCase: false,
  }
}

export function normalizeProductsWithVariants(products: Product[]) {
  const sourceProducts = products.filter((product) => !product.autoGeneratedCase)
  const normalizedSources = sourceProducts.map(normalizeSourceProduct)

  const ordered: Product[] = []
  normalizedSources.forEach((product) => {
    ordered.push(product)

    const relatedManualCases = normalizedSources.filter(
      (candidate) =>
        candidate.caseConfig &&
        candidate.id !== product.id &&
        candidate.parentProductId === product.id,
    )

    relatedManualCases.forEach((candidate) => {
      if (!ordered.some((entry) => entry.id === candidate.id)) {
        ordered.push(candidate)
      }
    })

  })

  const seen = new Set<string>()
  return ordered.filter((product) => {
    if (seen.has(product.id)) return false
    seen.add(product.id)
    return true
  })
}
